  export const productos = [
    {
        id: 1,
        name: " New Super Mario Bros.™ U Deluxe",
        price: 5000,
        descripcion: '¡Únete a Mario, Luigi y a sus amigos en cualquier momento y en cualquier lugar en una divertida aventura para uno o varios jugadores! Disfruta de dos aventuras de desplazamiento lateral con hasta tres amigos* e intenta salvar al Reino Champiñón. Incluye los juegos New Super Mario Bros. U y New Super Luigi U, ¡ambos incluyen a Nabbit y a Toadette como personajes jugables! ',
        image: " https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/games/switch/n/new-super-mario-bros-u-deluxe-switch/hero",
        stock: 3,
        categoryId: '1',
    },
    {
        id: 2,
        name: "Paper Mario™: The Origami King ",
        price: 6500,
        descripcion: "¡El reino ha sido devastado por una amenaza de origami! Únete a Mario y a su nueva compañera, Olivia, mientras luchan contra los malvados soldados plegados, reparan el paisaje dañado e intentan liberar el castillo de la princesa Peach de las garras del rey Olly en esta cómica aventura, exclusiva para la consola Nintendo Switch ™",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/games/switch/p/paper-mario-the-origami-king-switch/hero ",
        stock: 10,
        categoryId: '1',
    },
    {
        id: 3,
        name: "Super Mario Odyssey™ ",
        price: 5950,
        descripcion: "Explora increíbles lugares lejos del reino Champiñón al unirte a Mario y su nuevo amigo Cappy en una increíble aventura al mejor estilo trotamundos en 3D. Usa asombrosas habilidades como: el poder de capturar y controlar objetos, animales y enemigos; para conseguir energilunas necesarias para recargar la nave Odyssey y salvar a la princesa Peach de los planes de boda de Bowser. ",
        image: " https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/games/switch/s/super-mario-odyssey-switch/hero",
        stock: 7,
        categoryId: '1',
    },
    {
        id: 4,
        name: "Mario Kart™ 8 Deluxe  ",
        price: 6700,
        descripcion: "Un total de 48 pistas remasterizadas de la serie Mario Kart™ llegan corriendo al juego Mario Kart 8 Deluxe como contenido descargable de pago. ¡Las pistas incluyen aquellas basadas en ubicaciones del mundo real como Bulevares de París y Circuito Tokio del juego Mario Kart Tour, y pistas clásicas como Monte Chocolate de la versión del juego para la consola Nintendo 64 y Centro Cocotero de la versión del juego para la consola Wii! El contenido será lanzado en 6 olas de 8 pistas a partir del 18 de marzo de 2022 y hasta finales del año 2023. ",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/dlc/switch-dlc/mario-kart-8-deluxe-dlc/bundles/mario-kart-8-deluxe-booster-course-pass/image ",
        stock: 5,
        categoryId: '1',
    },
    {
        id: 5,
        name: "Super Mario Maker™ 2 ",
        price: 6300,
        descripcion: " Mario fans of the world, unite! Now you can play, create, and share* the side-scrolling Super Mario™ courses of your dreams in the Super Mario Maker™ 2 game, available exclusively on the Nintendo Switch™ system! Dive into the single-player Story Mode and play built-in courses to rebuild Princess Peach’s castle. Make your own courses, alone or together. And with a Nintendo Switch Online membership*, share your courses, access a near-endless supply made by others, enjoy online multiplayer, and more!",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_400/ncom/en_US/games/switch/s/super-mario-maker-2-switch/hero ",
        stock: 6,
        categoryId: '1',
    },
    {
        id: 6,
        name: "Mario Party™ Superstars ",
        price: 6250,
        descripcion: "Calling all superstars! The Mario Party™ series is back with 5 classic boards from the Nintendo 64 Mario Party games. Race to get the most stars (and sabotage your opponents) on boards like the stellar Space Land or the spooky Horror Land! Party at your own pace by suspending a game and picking up right where you left off! The tides can turn quickly in Mario Party, so stay vigilant, partygoers. All modes can be played online*, too!",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/games/switch/m/mario-party-superstars-switch/hero",
        stock: 9,
        categoryId: '1',
    },
    {
        id: 7,
        name: "Nintendo Switch - Neon Blue + Neon Red Joy-Con",
        price: 76500,
        descripcion: "At home, Nintendo Switch™ rests in the Nintendo Switch Dock that connects the system to the TV and lets you play with family and friends in the comfort of your living room. By simply lifting Nintendo Switch from the dock, the system will instantly transition to portable mode, and the same great gaming experience that was being enjoyed at home now travels with you. The portability of Nintendo Switch is enhanced by its",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/bo_15px_solid_white/f_auto/q_auto/dpr_auto/c_scale,w_700/ncom/en_US/products/hardware/nintendo-switch-red-blue/110478-nintendo-switch-neon-blue-neon-red-package-front-1200x675",
        stock: 5,
        categoryId: '2',
    },
    {
        id: 8,
        name: "Nintendo Switch Lite ---  Color Amarillo",
        price: 62900,
        descripcion: "Nintendo Switch Lite es una consola Nintendo Switch compacta y ligera que ha sido especialmente diseñada para el juego portátil. Con una cruz de control integrada y un pulido diseño es perfecta para jugar en el camino. La consola Nintendo Switch Lite es compatible con los juegos de la robusta colección de títulos para Nintendo Switch que son compatibles con el modo portátil. Si deseas una consola de videojuegos que sea solo para ti, Nintendo Switch Lite está lista para salir contigo donde quiera que estés",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/en_US/hardware/switch/nintendo-switch-lite/gallery/image01",
        stock: 3,
        categoryId: '2',
    },
    {
        id: 9,
        name: "Joy-Con™ (L)/(R) - The Legend of Zelda™",
        price: 6200,
        descripcion: "Disfruta del cautivador mundo del juego The Legend of Zelda™: Skyward Sword HD con este set de controles Joy-Con™ que cuenta con un diseño especial. El Joy-Con derecho está inspirado en la Espada Maestra, mientras que el control izquierdo está inspirado en el escudo hyliano",

        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/en_US/hardware/switch/accessories/joy-con-l-r-the-legend-of-zelda-skyward-sword-hd-edition/joy-con-pkg",
        stock: 3,
        categoryId: '3',

    },
    {
        id: 10,
        name: "Controles Joy-Con",
        price: 5900,
        descripcion: "Adquiere un set adicional (o dos) de Joy-Con, los controles que hacen posible nuevas maneras de jugar.",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/es_LA/hardware/switch/accessories/joy-con-l-r/thumbnail",
        stock: 4,
        categoryId: '3',

    },
    {
        id: 11,
        name: "Armazón de carga para controles Joy-Con",
        price: 9550,
        descripcion: "Combina el Joy-Con izquierdo y el Joy-Con derecho en un control más grande con este práctico armazón. Te permite cargar el Joy-Con mientras juegas, así no te perderás ni un momento",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/es_LA/hardware/switch/accessories/joy-con-charging-grip/gallery/image01",
        stock: 6,
        categoryId: '3',

    },
    {
        id: 12,
        name: "Nintendo Switch Carrying Case ",
        price: 9750,
        descripcion: "This case will help protect your Nintendo Switch™ system on the go",
        image: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/en_US/switch/site-design-update/hardware/switch/accessories/carrying-case-and-screen-protector/gallery/image02",
        stock: 8,
        categoryId: '3',

    },
]
export default productos;